### ISSUE TITLE
Filter for categories

### ISSUE THREAD

**Issue by jonsger** [giggls/opencampsitemap#1]
Hi,

first of all: Thank you for this nice little project. It already animated me to improve some camp sites in OpenStreetMap.

A nice feature still missing is filtering for categories or even facilities. E.g. only show campsites for groups on the map. Simple boxes with check marks should be enough for the beginning...

Jonathan

**Comment by giggls** [comment]
Unfortunately I'm not a very skilled Javascript programmer. I think I would need separate geojson layers to do this, which I currently do not have but would be very easy to do as far as the backend script is concerned.

Frankly, at the current state of (bad) tagging of the sites in general such a feature would IMO give the people a false impression. Currently most backcountry, group and nudist sites are almost certainly not tagged accordingly.
