### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by Bibi56** [giggls/opencampsitemap#11]
At some places, the icons at zoom level 10 is more or less drawing the coastal line:
https://opencampingmap.org/index.html.fr#10/48.0023/-4.0457/1/0/bef

Some buttons (+/- or icon shape or different sizes) should be available to use smaller icons.

There's another way but...
https://www.openstreetmap.org/way/131787506#map=18/48.28536/-4.52867
;-)

**Comment by giggls** [comment]
Smaller Icons are not a solution. I know, that I should cluster them. 
This is already on the [todo list](https://github.com/giggls/opencampsitemap/blob/master/TODO.md).

**Comment by Bibi56** [comment]
Intentionally I didn't mention as I don't think clusters is a good solution in this case. But feel free to disagree ;-). Well, if you group by kind and add a count, it may be a [good solution](http://geoserver.sortirdunucleaire.org/OpenLayers-2.10-rc2/examples/rsnGroupe.html?zoom=8&lat=6326640.94128&lon=-67514.32367&layers=FTFTTTFFFTB) indeed.

**Comment by giggls** [comment]
I am kind of a Noop when it comes to Javascript and front-end programming.
I thought I already mentioned this when announcing the map, that I am more of a backend guy. Well looks like I did not.
http://blog.gegg.us/2019/01/announcing-open-camping-map/
Anyway, if you want frontend features pull requests are almost certainly merged while feature requests may last forever.
