### ISSUE TITLE
Add hashtag to changesets from OpenCampingMap

### ISSUE THREAD

**Issue by jonsger** [giggls/opencampsitemap#14]
Hi,

I think it would be nice to create a hashtag for edits coming from the links in the UI. For example QwantMaps does this already:
https://github.com/QwantResearch/erdapfel/blob/master/src/components/OsmContribution.jsx#L7

So I tried this as well but somehow it doesn't work:
```
diff --git a/site-feature.js b/site-feature.js
index 9fcb27e..502d8a0 100644
--- a/site-feature.js
+++ b/site-feature.js
@@ -345,6 +345,6 @@ function editInJOSM(fdata) {
 function editInID(fdata) {
   var osm_id=fdata['id'].split('/');  
   var url = "https://www.openstreetmap.org/edit?editor=id&lon="+fdata.geometry['coordinates'][0];
-  url += "&lat="+fdata.geometry['coordinates'][1]+"&zoom="+map.getZoom()+"&"+osm_id[osm_id.length-2]+"="+osm_id[osm_id.length-1];;
+  url += "&lat="+fdata.geometry['coordinates'][1]+"&hashtags=OpenCampingMap"+"&zoom="+map.getZoom()+"&"+osm_id[osm_id.length-2]+"="+osm_id[osm_id.length-1];
   var win = window.open(url, '_blank');
 }
```

**Comment by giggls** [comment]
Well I never did a single edit using id.

**Comment by jonsger** [comment]
Others may [use ID](https://wiki.openstreetmap.org/wiki/Editor_usage_stats#by_number_of_users_.28distinct_uids.29).

And it looks like that JOSM has hashtag support as well: https://josm.openstreetmap.de/ticket/15537

**Comment by giggls** [comment]
I changed the code running on https://camping.openstreetmap.de/map-dev/ see if this works.

**Comment by jonsger** [comment]
> I changed the code running on https://camping.openstreetmap.de/map-dev/ see if this works.

It does not work. It's the same like I do locally. The `&hashtags=foo` ends up in the URL but there are no hashtags prefilled in the changeset comment section...

**Comment by giggls** [comment]
We will not get this to work without a specification about how the URL has to look like.

**Comment by jonsger** [comment]
https://github.com/openstreetmap/iD/blob/develop/API.md#url-parameters doesn't look like we are wrong.

**Comment by wtimme** [comment]
The little detail in the documentation was this bit:

> [...] the following parameters are available **in the hash portion of the URL**:

With "hash portion", they mean the information that goes after the `#`. In #32, I have added support for the hashtag `#OpenCampingMap` with iD.
