### ISSUE TITLE
Map down

### ISSUE THREAD

**Issue by limex** [giggls/opencampsitemap#19]
Hi,
first: Thanks for your great work.
second: I think the map is down.  https://opencampingmap.org/ shown nothing

Best Regards 
Günther

**Comment by giggls** [comment]
Server update to Debian 11 is finished now.

However, I will also use this system update for adding support for relations of type=site and doing a reimport of the POI database (PostgreSQL 13). This will likely take until tomorrow.

So now there is at least the intended maintenance page :-)
