### ISSUE TITLE
Help for tagging

### ISSUE THREAD

**Issue by JBacc1** [giggls/opencampsitemap#20]
There is no complete documentation on which tags are used in the project. 
"Infotip" when mouse hovers over the icons on the first menu showing which tag/key is needed to have the info would help.

**Comment by giggls** [comment]
Well, the map has a complete legend and tagging is documented in the wiki.
Maybe our icons should also be added to the wiki.

It is also possible to open the related OSM object using the Bug icon to visualize its tagging on e.g. https://www.openstreetmap.org/way/211554090

You are suggesting tagging tooltips on the legend, right? Well I do not really like this idea.

First it is more complicated in many cases than just tagging **key=value.**

Often there are three possibilities of tagging for making an icon to be shown on the map.
Let me explain this using the firepit icon:
![firepit](https://user-images.githubusercontent.com/7996314/132089607-be369b70-d458-461e-b91e-249367d4c94a.png)

This icon is shown in one of the following cases:

1. A node, closed way or multipolygon tagged **tourism=camp_site** is also tagged **openfire=yes**
2. A closed way or multipolygon tagged **tourism=camp_site** contains an object tagged **leisure = firepit**
3. A relation tagged **tourism=camp_site** and **type = site** contains an object tagged **leisure = firepit**

**Comment by giggls** [comment]
BTW, here is a site I consider nicely mapped.
https://www.opencampingmap.org/#18/49.12700/10.86593/1/1/bef/way/26527870

**Comment by JBacc1** [comment]
The problem I had was that I could not find the tag power_supply=* in the wiki (and in that camping, the value =no is a surprise for most visitors). The wiki camping page in not complete (sure, I could add this specific tag), and the opencampingmap site does not list the tags used. 
I'm not sure I'm seeing a solution here if there is no minimal documentation for at least one way of adding the info used in this site.

**Comment by giggls** [comment]
While power_supply=no needs to be tagged on the site itself for obvious reasons there are multiple ways of getting this to yes. The preferred way would be to acquire the power supplies themselves (amenity = power_supply) as I did here:
https://www.opencampingmap.org/#19/48.64596/8.03393/1/1/bef
BTW the wiki **does** contain the power_supply key.

**Comment by giggls** [comment]
The more I think about this the more I think we should add the SVG-icons to the wiki.

**Comment by giggls** [comment]
OK, I added the icons to the wiki (German and English for now) thus closing this.
