### ISSUE TITLE
Show internet_access=no

### ISSUE THREAD

**Issue by JBacc1** [giggls/opencampsitemap#21]
Internet access is now so commonplace in campings that I guess a specific icon for internet_access=no would be useful.

**Comment by giggls** [comment]
Adding a crossed out wifi icon and "no internet access" as a tooltip would be easy.
Do you approve this?

**Comment by giggls** [comment]
Hm likely I did not support internet_access=no because I did not come up with a good Idea for a Logo.

**Comment by JBacc1** [comment]
Hm, just using the logo of internet_access=wlan, but with a red contour and a red diagonal? Just like the no toilets, no caravans, no drinking water?

**Comment by giggls** [comment]
This is what I meant with "a crossed out wifi icon". However one could interpret this as no-wifi instead of no internet access.

**Comment by JBacc1** [comment]
Great!
