### ISSUE TITLE
Wildcamping sites need own symbol

### ISSUE THREAD

**Issue by Spanholz** [giggls/opencampsitemap#3]
Currently Wild camping sites are mapped as "camping caravaning" and the tag camp_type=wildcamp seems to be ignored. For example in this area: https://opencampingmap.org/index.html.en#11/67.9275/18.4138

Another symbol or no rendering of these nodes should be considered. I also contacted the contributor of all these wildcamping nodes as it is probably not useful to add so many wildcamping sites.

**Comment by giggls** [comment]
The mapping is based on established tagging with "camping caravaning" being the default:

Code is here:
https://github.com/giggls/osmpoidb/blob/master/gen_mview_poi_campsites.sql

The established tagging for your stuff will likely be backcountry=yes or (tents=yes and caravans=no).
According to https://taginfo.openstreetmap.org/ there are 3645 backcountry campsites and only 68 with camp_type=wildcamp in the database.

Examples for tagging backcountry campsites:
https://www.openstreetmap.org/way/503233738 in Germany
https://www.openstreetmap.org/node/3064201491 in Yellowstone USA
