### ISSUE TITLE
Not revieweable POIs

### ISSUE THREAD

**Issue by cascafico** [giggls/opencampsitemap#34]
As far I understand, the red exclamation mark [(example)](https://opencampingmap.org/#16/46.0159/13.3922/0/1/410/node/4403910000) appears in case there is no value for OSM tag "name".  
  
Unfortunately in such case there is no chance to review the place. Besides, text link "Unnamed campsite" points to a [non existent page](https://opencampingmap.org/undefined).

**Comment by giggls** [comment]
A site is marked with the the red exclamation mark in case there is *no* name tag or *only* a name tag. The only bug i see here is that there should be no link pointing to undefined which I need to fix. 

Enabling the review function for unnamed sites is technically impossible as a name is needed for Mangrove. So I will try to fix this unnamed stuff and close this issue as impossible to fix then.
