### ISSUE TITLE
How to correctly map/tag multiple campsites located in a park?

### ISSUE THREAD

**Issue by i-ky** [giggls/opencampsitemap#37]
There is ["Esena Pārdaugavas dārzi" park](https://www.openstreetmap.org/relation/12857959) with three camp sites inside: [G1](https://www.openstreetmap.org/way/975243864), [G2](https://www.openstreetmap.org/way/975243865) and [G3](https://www.openstreetmap.org/way/975243863).

![Map of the park](https://static.wixstatic.com/media/fc0721_c9ce61b1698a42c492ba3ad01a9ec478~mv2.png/v1/fill/w_980,h_893,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/Karte.png)

All three show up on OpenCampingMap as "buggy" due to missing contact information:
1. https://opencampingmap.org/#16/56.9832/24.0532/0/1/bef/way/975243864
1. https://opencampingmap.org/#16/56.9832/24.0532/0/1/bef/way/975243865
1. https://opencampingmap.org/#16/56.9832/24.0532/0/1/bef/way/975243863

There is also an [OSM note](https://www.openstreetmap.org/note/3290321) regarding missing contact info.

However, enclosing park relation has correct website information and there are no individual websites for G1, G2 and G3. Would it be possible for OpenCampingMap to pick up information from enclosing features? Or would you suggest to duplicate information for every camp site? Or something else entirely? Maybe adding [`site` relation for G1, G2 and G3](https://blog.geggus.net/2021/09/announcing-support-for-site-relations-in-opencampingmap/) with website tag?

**Comment by flohoff** [comment]
Hi,
i was the opener of the original OSM Note as i was not able to find additional informations on those camp sites. I have no clue on how to fix this but as this is some park which seems to share the same Entry/Reception and just has some camp spots a solution would be to remove the individual camp site nodes, and put the information on camping possibilities on the relation making up the Park?

**Comment by giggls** [comment]
First of all I don't think that github issues are the right place for tagging discussions.

This said here is what I would do:

If this is a public park where camping is permitted at these 3 Areas only I would tag the park as tourism=camp_site and change G1, G2 and G2 to tourism=camp_pitch and **name** to **ref**.

In addition add additionals tags to make clear that caravans are not permitted etc.
https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcamp_site

**Comment by giggls** [comment]
Adding a node tagged tourism=camp_site and an additional site relation will also work. G1-G3 should be tagged as camp_pitch in any case.

I would choose this option if the main purpose of the area is not camping.

In this case I would also add a description tag describing this fact.

**Comment by i-ky** [comment]
@giggls, thank you for a prompt response!
