### ISSUE TITLE
Link to Navigation App

### ISSUE THREAD

**Issue by PascalBru** [giggls/opencampsitemap#38]
Is there a way to have an link for navigation app like GoogleMaps or others? Couldn’t find a way to get the coordinates for the navigation.

**Comment by giggls** [comment]
I will certainly not adding something which links to Google.
However displaying the Coordinates of the Campsite Icon would be easy to do.

**Comment by PascalBru** [comment]
Google was just an example coordinates would be fine then every one can use his preferred app for navigation. Are you going to add it or would you tell me in which file I could start and then I will make an PR in December. 

THX for your work it’s a great website?
