### ISSUE TITLE
OpenCampingMap should have a different icon for campings that are only meant for permanent residents

### ISSUE THREAD

**Issue by benderydt** [giggls/opencampsitemap#39]
I'd like to have a visual distinction between campings open for regular travellers and those that are only open for permanent residents, that is camp sites that do not have free pitches and will not accept passers by nor short stays.

One of these kind of campings is "Le Roi Soleil" in Mariembourg, Belgium:

https://opencampingmap.org/#12/50.0825/4.4378/0/1/bef/way/651694145

Another example is "Camping Waterschap" in Viersel, Belgium:

https://opencampingmap.org/#12/51.1897/4.5717/0/1/bef/node/497225468

I have tagged both campings with permanent_camping=only but that does not make any difference in how the camping is displayed. 

As these kind of campings are most likely not of interest to the kind of people using OpenCampingMap, I would like to have a clearer distinction between these and regular camp sites.

**Comment by giggls** [comment]
I usually tag those sites as private=yes and then there already is a different logo.
Example: https://opencampingmap.org/#14/47.8132/8.1654/1/1/bef/way/111450557

Arguably permanent_camping=only should imply access=private even if not explicitly tagged.

**Comment by benderydt** [comment]
OK, I'll do that even though it doesn't make that much sense IMHO. These campings are as private or public as any other camp site. In the case of Camping Waterschap they're actually advertising that they have new free pitches for a season or a year, they just don't want any short term camping.

Thanks for the quick reply anyway.

**Comment by giggls** [comment]
As I already wrote. One could argue that those sites are always private as pitches are only available there for terms comparable to flats or houses.
What I should probably do is to treat permanent_camping=only the same as access=private as far as the logo is concerned.

**Comment by benderydt** [comment]
> What I should probably do is to treat permanent_camping=only the same as access=private as far as the logo is concerned.

That'll do for me.
