### ISSUE TITLE
OpenCampingMap should display "contact:mobile" telephone numbers

### ISSUE THREAD

**Issue by benderydt** [giggls/opencampsitemap#40]
OpenCampingMap does not display telephone numbers tagged as "contact:mobile" but it should.

Example, camping Gatsch Eck:

https://opencampingmap.org/#17/53.51500/13.20545/0/1/bef/way/724615543

This camping is tagged with both "contact:mobile = +49 1719565112" and "phone = +49 395 5665152" but only the phone number is shown.

**Comment by giggls** [comment]
Right. Currently not shown. However easy to add.
