### ISSUE TITLE
Review displayed for wrong camp site

### ISSUE THREAD

**Issue by JIDB1** [giggls/opencampsitemap#45]
If I first click on a camp site with a mangroove review like
https://opencampingmap.org/en/way/394409172#12/50.3390/1.6273/1/1/bef
and just after that on one without name (and without review) like
https://opencampingmap.org/en/way/418115857#12/50.3390/1.6273/1/1/bef
then the review of the first camp site remains displayed for the second camp site
(You need to click the second camp site on the map, not just follow the link).

The problem can be reproduced with other camp site without name like
https://opencampingmap.org/en/way/268367392#12/50.3390/1.6273/1/1/bef
bot not with some with a name like
https://opencampingmap.org/en/way/437423564#12/50.3390/1.6273/1/1/bef

**Comment by giggls** [comment]
Yes clearly a bug!

Name is the only Anchor for mangrove thus likely the difference between named and unnamed sites. Unnamed sites should never display any review.

Unfortunately the mangrove code was developed by @wtimme not me. However I will see what I can do.

**Comment by giggls** [comment]
@wtimme  I would also like to have the reviews in the static page (with javascript disabled) to make it indexable. How difficult would this be?

**Comment by wtimme** [comment]
I feel like this deserves a dedicated GitHub issue.

First of all, what is the goal of this? Like, why do you wish to do that? To have more traffic on the site?

Technically, I feel that this should be discussed further together with the Mangrove team. What we are doing right now is querying their API for each and every camp site that the user clicks. I'm not sure that doing this for the whole camp site database is desirable. Rather, it sounds like a good way to DoS their backend.

One approach could be to get a data dump from the Mangrove team, ideally already filtered by camp sites. And then we would need to cross-reference their data with the camp sites in our database.

**Comment by JIDB1** [comment]
Thanks for the very fast reaction!
