### ISSUE TITLE
Small changes to interface

### ISSUE THREAD

**Issue by orson-69** [giggls/opencampsitemap#55]
I propose a small change to the interface, as simplified in the attachment.

Maybe it's just my idea, putting the icons on the type of vehicles the campsite accepts in different rows, compared to the services, gives a bit more order.

I would also suggest removing the Fax indication in the lower part, which I think is almost unused by now.

Instead, I have seen that many campsites expressly indicate the mobile phone next to the landline, and several highlight the contact for any WhatsApp messages.
So I think it would be useful to insert the mobile phone and the WhatsApp contact. Maybe by putting the code on the site to send the WhatsApp message.

The openstreetmap tags are phone_mobile and contact:whatsapp respectively
![Immagine 2024-10-15 111155](https://github.com/user-attachments/assets/d6d9672f-0d30-4f5d-9364-5ad715571889)

**Comment by giggls** [comment]
Yes, probably a good idea to add at least a Newline and/or separator between accommodation types and site features.

However *contact:mobile* is already supported as are *contact:facebook*, *contact:instagram* and *contact:twitter*

Example: https://opencampingmap.org/de/way/225468990

Looks like I should also map the legacy mobile tag to contact:mobile as I did with the other legacy contact items.

Given the list at:

[https://wiki.openstreetmap.org/wiki/Key:contact:*](https://wiki.openstreetmap.org/wiki/Key:contact:*)

I should likely add a few more.

I will close this issue if I added the changes.

**Comment by giggls** [comment]
Just for your info.

* I already had support for *contact:mobile* but did not support the legacy *mobile* tag. Code does support both now.
* Code already supported any contact:<something> which will include Whatsapp.
* I did just add add a newline after accommodation icons because a horizontal line did not look that nice.
