### ISSUE TITLE
Tagging of showers

### ISSUE THREAD

**Issue by jonsger** [giggls/opencampsitemap#6]
`group_only` camping sites often tend to have a sanitary building with toilets and showers. I tag those buildings as `amenity=toilets` and `shower=yes`. If I do it this way, the shower doesn't get recognized by opencampsitemap.

Should I tag it differently or should we add some statement to https://github.com/giggls/osmpoidb/blob/master/gen_mview_poi_campsites.sql in order to catch them?

**Comment by giggls** [comment]
Yep, should be added to the backend at https://github.com/giggls/osmpoidb/blob/master/gen_mview_poi_campsites.sql Please re-open the issue there or better yet send a pull-request :)

**Comment by giggls** [comment]
OK, fixed in 
https://github.com/giggls/osmpoidb/commit/66747a3c348f8b65d7c4ad3005ef9c00d3595224
